config/routes.rb
Rails.application.routes.draw do
  captcha_route
  devise_for :accounts, controllers: {
    registrations: 'accounts/registrations',
    sessions: 'accounts/sessions',
    passwords: 'accounts/passwords'
  }
  resources :posts, param: :uuid
  resources :properties, param: :uuid

  get "/blog" => "posts#latest", as: :blog

  #admin routes
  get "/accounts" => 'admin#accounts', as: :accounts

  get "dashboard" => 'dashboard#index', as: :dashboard
  get "profile/:uuid" => 'dashboard#profile', as: :profile
  post "/agent/message" => "properties#email_agent", as: :email_agent


  root to: "public#main"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/nav/_admin.html.erb
<li class="nav-item">
  <%= link_to accounts_path, class:"nav-link" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
    Accounts <span class="sr-only">(current)</span>
  <% end %>
</li>
<li class="nav-item">
  <%= link_to properties_path, class:"nav-link" do %>
  <i data-feather="package"></i>
    Properties
  <% end %>
</li>
<li class="nav-item">
  <%= link_to posts_path, class:"nav-link" do %>
    <i data-feather="calendar"></i>
    Blog Posts
  <% end %>
</li>
<!-- <li class="nav-item">
  <a class="nav-link" href="#">
    <i data-feather="users"></i>
    Adverts
  </a>
</li> -->

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">TSB Properties</a>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to "Log out", destroy_account_session_path, method: :delete, class: "nav-link"%>
    </li>
  </ul>
</nav>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container">
    <a class="navbar-brand" href="  <%= account_signed_in? ? dashboard_path: root_path %>">TSB Properties</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <% if account_signed_in? %>
            <%= link_to "Dashboard", dashboard_path, class: "nav-link"%>
          <% else %>
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          <%end%>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="#">Latest</a>
        </li> -->

        <!-- <li class="nav-item">
          <a class="nav-link" href="#">Advertising</a>
        </li> -->

        <li class="nav-item">
          <%= link_to "Blog", blog_path, class: "nav-link"%>
        </li>
      </ul>



      <% if account_signed_in? %>
        <%= link_to "Log Out", destroy_account_session_path, method: :delete, class: "btn btn-secondary float-sm-right"%>
      <%else %>
        <%= link_to "Log In", new_account_session_path, class:"btn btn-secondary mr-2 float-sm-right"%>
        <%= link_to "Sign Up", new_account_registration_path, class:"btn btn-success float-sm-right"%>
      <%end%>

    </div>
  </div>
</nav>

app/views/layouts/nav/_sidebar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      <%= render "layouts/nav/#{current_account.admin? ? 'admin' : 'user'}" %>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Settings</span>
    </h6>

    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <%= link_to profile_path(uuid: current_account.uuid), class:"nav-link" do %>
          <i data-feather="file-text"></i>
          My Profile
          <% end %>
      </li>
      <li class="nav-item">
        <%= link_to edit_account_registration_path, class:"nav-link" do %>
          <i data-feather="settings"></i>
          Account Settings
        <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/nav/_user.html.erb
<li class="nav-item">
  <%= link_to dashboard_path, class:"nav-link" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
    Dashboard <span class="sr-only">(current)</span>
  <% end %>
</li>
<li class="nav-item">
  <%= link_to properties_path, class:"nav-link" do %>
  <i data-feather="package"></i>
    Properties
  <% end %>
</li>
<!-- <li class="nav-item">
  <a class="nav-link" href="#">
    <i data-feather="calendar"></i>
    Viewings
  </a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">
    <i data-feather="users"></i>
    Contacts
  </a>
</li> -->