config/routes.rb
Rails.application.routes.draw do
  captcha_route
  devise_for :accounts, controllers: {
    registrations: 'accounts/registrations',
    sessions: 'accounts/sessions',
    passwords: 'accounts/passwords'
  }
  resources :posts, param: :uuid
  resources :properties, param: :uuid

  get "/blog" => "posts#latest", as: :blog

  #admin routes
  get "/accounts" => 'admin#accounts', as: :accounts

  get "dashboard" => 'dashboard#index', as: :dashboard
  get "profile/:uuid" => 'dashboard#profile', as: :profile
  post "/agent/message" => "properties#email_agent", as: :email_agent


  root to: "public#main"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :account, :optional => true

  scope :latest_properties, -> { order created_at: :desc}

  scope :sold, -> { where(for_sale: true, status: "sold") }
  scope :for_sale, -> { where(for_sale: true, status: "available") }
  scope :leased, -> { where(for_sale: false, status: "leased") }
  scope :for_rent, -> { where(for_sale: false, status: "available") }

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!, only: [:new, :create, :destroy]
  before_action :set_sidebar, except: [:show]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @agent = @property.account
    @agent_properties = Property.where(account_id: @agent.id).where.not(id: @property.id) if @agent && @property
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
    @property.account_id = current_account.id
    respond_to do |format|
      if @property.save
        @property.reload
        format.html { redirect_to property_path(uuid: @property.uuid), notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_path(uuid: @property.uuid), notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def email_agent
    agent_id = params[:agent_id]
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]
    message = params[:message]

    ContactMailer.email_agent( agent_id, first_name, last_name, email, message ).deliver_now

      respond_to do |format|
        format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find_by_uuid(params[:uuid])
    end

    def set_sidebar
      @show_sidebar = true
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :address, :price, :integer, :rooms, :bathrooms, :parking_spaces, :for_sale, :status, :available_date, :details, :photo_cache, :photo)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper

  def  property_thumbnail property
      img = property.photo.present? ? property.photo.thumb.url : "placeholder.jpg"
      image_tag img, class: "property-thumb"
    end

    def  property_thumbnail_url property
      property.photo.present? ? property.photo.thumb.url : "placeholder.jpg"
    end

    def  property_photo_url property
        property.photo.present? ? property.photo.url : asset_url("placeholder.jpg")
      end

end

app/views/properties/_agent_details.html.erb
<div class="">
<div class="text-center border p-4 pb-4 ml-lg-4">
  <div class="mb-2">
    <%= profile_picture @agent %>
  </div>
  <h3 class="h4 m-0"><%= sanitize @agent.full_name %></h3>
  <p><%= sanitize @agent.company %></p>

    <div class="row">
      <div class="col-12">
        <button class="btn btn-block btn-info text-uppercase mb-3" id="show-tel" data-telephone="<%= @agent.telephone %>"><i class="fas fa-phone mr-2"></i><span> Call </span><button>
      </div>
    </div>

  <div class="row">
      <div class="col-md-6 pr-1">
        <%= link_to "Profile", profile_path(uuid: @agent.uuid), class: "btn btn-secondary btn-block text-uppercase" %>
      </div>
      <div class="col-md-6 pl-1">
        <button class="btn btn-block btn-success text-uppercase" data-toggle="modal" data-target="#contact-modal"> Email <button>
      </div>
    </div>
  </div>
</div>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <%= render "layouts/validation", item: @property %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price, "Total Price (For Sale) / Monthly Price (Rental)"%>
    <%= form.text_field :price, class: "form-control" %>
  </div>


  <!-- <div class="field">
    <%= form.label :integer %>
    <%= form.text_field :integer %>
  </div> -->

  <div class="form-group">
    <%= form.label :rooms %>
    <%= form.number_field :rooms, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :bathrooms %>
    <%= form.text_field :bathrooms, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :parking_spaces %>
    <%= form.number_field :parking_spaces, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :for_sale %>
    <%= form.select :for_sale, options_for_select({"Yes" => true, "No" => false}, @property.for_sale), class: "form-control" %>
  </div>

  <div class="form-group">
    <% opts = @property.for_sale? ? { "Available" => "available", "Sold" => "sold" } : { "Available" => "available", "Leased" => "leased" }%>
    <%= form.label :status %>
    <%= form.select :status, options_for_select(opts, @property.status), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :available_date %>
    <%= form.date_field :available_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :details %>
    <%= form.text_area :details, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :photo %>
    <%= form.file_field :photo, class: "form-control" %>
    <%= form.hidden_field :photo_cache%>

    <% if property.photo.present? %>
      <%= image_tag property.photo.thumb.url, class:"mt-4" %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.submit "Save Property", class: "btn btn-success" %>
  </div>
<% end %>

app/views/properties/_list.html.erb
<% properties.each do |property| %>

  <div class="col-4">
    <div class="property border">

      <div class="property-thumb" style="background-image: url(<%= property_thumbnail_url(property) %>)">
        <%= sanitize link_to "", property_path(uuid: property.uuid) %>
      </div>

      <div class="property-summary p-3">
        <h3 class="h5"><%= sanitize link_to property.name, property_path(uuid: property.uuid), scrubber: PropertyScrubber.new, class:"text-dark"%></h3>

        <span class="mr-2"><i class="fas fa-bed text-muted ml-1"></i><%= property.rooms %></span>
        <span class="mr-2"><i class="fas fa-bath text-muted ml-1"></i><%= property.bathrooms %></span>
        <span class="mr-2"><i class="fas fa-car text-muted ml-1"></i><%= property.parking_spaces %></span>

        <p class="mt-2"><%= sanitize property.address, scrubber: PropertyScrubber.new %></p>
      </div>
  </div>
</div>

<% end %>

app/views/properties/_profile_contact_details.html.erb
<div class="text-center">
  <div class="mb-2">
    <%= profile_picture agent %>
  </div>
  <h3 class="h4 m-0"><%= sanitize agent.full_name %></h3>
  <p><%= sanitize agent.company %></p>

    <div class="row justify-content-lg-center">
      <div class="col-lg-8">
        <button class="btn btn-block btn-info text-uppercase mb-1" id="show-tel" data-telephone="<%= agent.telephone %>"><i class="fas fa-phone mr-2"></i><span> Call </span><button>
      </div>
      <div class="col-lg-8">
        <button class="btn btn-block btn-success text-uppercase" data-toggle="modal" data-target="#contact-modal"> <i class="fas fa-envelope mr-2"></i>Email <button>
      </div>
    </div>
  </div>

app/views/properties/_send_email_modal.html.erb
<div class="modal fade" id="contact-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message For <%= agent.first_name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag email_agent_path, id: "email-agent" do %>
          <%= hidden_field_tag :agent_id, agent.id %>

          <div class="form-group">
            <label for="message-first-name" class="col-form-label">First Name:</label>
            <%= text_field_tag :first_name, nil, class: "form-control", id: "message-first-name" %>
          </div>

          <div class="form-group">
            <label for="message-last-name" class="col-form-label">Last Name:</label>
            <%= text_field_tag :last_name, nil, class: "form-control", id: "message-last-name" %>
          </div>

          <div class="form-group">
            <label for="message-email" class="col-form-label">Email:</label>
            <%= text_field_tag :email, nil, class: "form-control", id: "message-email" %>
          </div>

          <div class="form-group">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-success" id="send-message-to-agent">Send message</button>
      </div>
    </div>
  </div>
</div>

app/views/properties/edit.html.erb
<h1 class="h3">Editing Property</h1>

<%= render 'form', property: @property %>

app/views/properties/index.html.erb
<h1 class="h3">Properties</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <!-- <th>Integer</th> -->
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= sanitize property.name %></td>
        <td><%= sanitize property.address %></td>
        <td><%= property.price %></td>
        <td><%= property.integer %></td>
        <td><%= property.rooms %></td>
        <td><%= property.bathrooms %></td>
        <td><%= link_to 'Show', property_path(uuid: property.uuid) %></td>
        <td><%= link_to 'Edit', edit_property_path(uuid: property.uuid) %></td>
        <td><%= link_to 'Destroy', property_path(uuid: property.uuid), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path, class: "btn btn-success" %>

app/views/properties/new.html.erb
<h1 class="h3">New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
    <div class="property-main-photo" style="background-image:url('<%= property_photo_url @property %>')">
      <div class="photo-overlay">
      </div>
    </div>

      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <div class="row">
              <div class="col-lg-6">
                <p class="h4 mb-0"> <%= @property.for_sale? ? "For Sale" : "For Rent" %> </p>
                <p class="mb-2"> <%= @property.address %> </p>
                <p class="h2 mb-3">
                  <% if @property.for_sale? %>
                    <%=@property.price > 0 ? number_to_currency(@property.price, precision: 0) : "Offers Accepted" %>
                  <% else %>
                    <%=@property.price > 0 ? number_to_currency(@property.price, precision: 0) : "Open For Enquiries" %> / Month
                  <% end %>
                </p>
              </div>
              <div class="col-lg-6 text-center">
                <div class="row mt-sm-3 bg-light p-3">
                  <div class="col-4">
                    <i class="fas fa-bed text-muted ml-0"></i><br/>
                    <small><%= @property.rooms%> Bedrooms </small>
                </div>
                <div class="col-4">
                  <i class="fas fa-bath text-muted ml-0"></i><br/>
                  <small><%= @property.bathrooms %> Bathrooms </small>
                </div>
                <div class="col-4">
                  <i class="fas fa-car text-muted ml-0"></i><br/>
                  <small><%= @property.parking_spaces%> Parking </small>
                </div>
              </div>
            </div>
          </div>

          <div class="row border-top border-bottom mt-4 mb-4 pt-4 pb-4">
            <div class="col-6">
              <% if @property.for_sale? %>
                <strong><%= link_to "Estimated Monthly Repayments of #{ number_to_currency ((@property.price - (@property.price * 0.1)) / 360), precision: 0 } *", "#", class: "text-success" %></strong>
              <% else %>
                <strong>Available From <%= @property.available_date.strftime("%a") %>, <%= @property.available_date.day.ordinalize %> <%= @property.available_date.strftime("%B") %> <%= @property.available_date.strftime("%Y") %></strong>
              <% end %>
            </div>
            <div class="col-6 text-right">
              <strong><%= link_to "Can I Afford This Property?", "#", class: "text-success" %></strong>
            </div>
          </div>

          <div class="row">
            <div class="col">
            <p class="h4"><%= sanitize @property.name, scrubber: PropertyScrubber.new %></p>
            <p class="h5"> Property Description </p>

            <div id="prop-details">
              <%= simple_format @property.details %>
            </div>

            <button class="btn btn-outline-info mt-3" id="toggleDetails"> Show More </button>

            <% if @property.for_sale %>
              <p class="mt-5">This rate is based on a 30 year mortgage, after making an initial 10% down payment.</p>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-lg-4">
        <%= render "properties/agent_details" %>

        <iframe class="ml-lg-4 mt-3" width="320" height="240" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCaJtibJ3V28ORC77tgRFHbVbEFXRi-xf8&q=<%= @property.address.to_param %>" allowfullscreen></iframe>
      </div>
    </div>
  </div>

  <section class="mt-5 mb-5">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <p class="h3 mb-3"> Other Properties By This Agent</p>
        </div>
          <%= render "properties/list", properties: @agent_properties %>
      </div>
    </div>
  </section>

<%= render "properties/send_email_modal", agent: @agent %>