config/routes.rb
Rails.application.routes.draw do
  captcha_route
  devise_for :accounts, controllers: {
    registrations: 'accounts/registrations',
    sessions: 'accounts/sessions',
    passwords: 'accounts/passwords'
  }
  resources :posts, param: :uuid
  resources :properties, param: :uuid

  get "/blog" => "posts#latest", as: :blog

  #admin routes
  get "/accounts" => 'admin#accounts', as: :accounts

  get "dashboard" => 'dashboard#index', as: :dashboard
  get "profile/:uuid" => 'dashboard#profile', as: :profile
  post "/agent/message" => "properties#email_agent", as: :email_agent


  root to: "public#main"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PhotoUploader

  scope :active, -> { where(active: true) }
  scope :latest, -> { order created_at: :desc}


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, only: [:new, :create]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :can_access?, except: [:show, :latest]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  def latest
    @posts = Post.active
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_path(uuid: @post.uuid), notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_path(uuid: @post.uuid), notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by_uuid(params[:uuid])
    end

    def can_access?
      @show_sidebar = true

      unless current_account.admin?
        redirect_to root_url, flash: {danger: "You do not have access to view this page"} and return
      end
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :url, :summary, :body, :image, :active)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def  post_thumbnail_url post
    post.image.present? ? post.image.thumb.url : "placeholder.jpg"
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :summary %>
    <%= form.text_field :summary, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
    <%= form.hidden_field :image_cache%>

    <% if @post.image.present? %>
      <%= image_tag @post.image.thumb.url, class:"mt-4" %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_list.html.erb
<% posts.each do |post| %>
  <div class="col-sm-6 col-md-4 col-lg-3 mb-3">
    <div class="property border">
      <div class="property-thumb" style="background-image: url(<%= post_thumbnail_url(post) %>)">
        <%= link_to "", post_path(uuid: post.uuid) %>
      </div>
      <div class="property-summary p-3">
        <h3 class="h5"><%= sanitize link_to post.title, post_path(uuid: post.uuid), class:"text-dark"%></h3>

        <p class="mt-2"><%= sanitize post.summary %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', post_path(uuid: @post.uuid) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Summary</th>
      <th>Body</th>
      <th>Image</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= sanitize post.title %></td>
        <td><%= post.url %></td>
        <td><%= sanitize post.summary %></td>
        <td><%= sanitize post.body %></td>
        <td><%= post.image %></td>
        <td><%= post.active %></td>
        <td><%= link_to 'Show', post_path(uuid: post.uuid) %></td>
        <td><%= link_to 'Edit', edit_post_path(uuid: post.uuid) %></td>
        <td><%= link_to 'Destroy', post_path(uuid: post.uuid), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/latest.html.erb
<main role="main" class="main-banner" id="blog-banner">
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-4">Latest Blog Posts</h1>
      <p>Stay Up To Date With The Latest News At TSB Properties!</p>
    </div>
  </div>
  </main>

<div class="container">
  <% if @posts.empty? %>
    <p> No Posts To Display. </p>
  <% else %>
    <% @posts.each do |post| %>
    <div class="row">
      <div class="col">
        <h2><%= post.title %></h2>
        <p><%= sanitize post.summary%></p>
        <%= link_to "Read More", post_path(uuid: post.uuid), class: "btn btn-success" %>
        <hr />
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<main role="main">
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-4"><%= @post.title %></h1>
      <p class="text-muted pl-2"><em>Posted <%= time_ago_in_words @post.created_at %></em></p>
    </div>
  </div>
</main>
<div class="container">
    <%= image_tag @post.image.thumb.url, class: "float-right mb-4 ml-4" if @post.image.present? %>
    <%= sanitize simple_format @post.body %>

    <p><%= link_to "View Latest Blog Posts", blog_path %></p>
</div>